FROM nvidia/cuda:11.1.1-runtime-ubuntu20.04
WORKDIR /SA
COPY . .

# install packages
COPY dockerfiles/requirements.txt .
COPY dockerfiles/vimrc /root/.vimrc
COPY dockerfiles/zshrc /root/.zshrc
COPY dockerfiles/oh-my-zsh /root/.oh-my-zsh
COPY dockerfiles/tmux.conf /root/.tmux.conf
COPY dockerfiles/torch-1.10.1+cu111-cp38-cp38-linux_x86_64.whl .
ENV DEBIAN_FRONTEND noninteractive #https://stackoverflow.com/questions/59692797/how-to-fill-user-input-for-interactive-command-for-run-command
RUN apt-get update -y && \
    apt-get install -y vim zsh tmux tree htop python3.8 python3-pip && \
    apt-get update -y && \
    rm /usr/bin/python3 && ln -s /usr/bin/python3.8 /usr/bin/python3 && \
    python3 -m pip install --upgrade pip && \
    pip install torch-1.10.1+cu111-cp38-cp38-linux_x86_64.whl && \
    pip install torchvision==0.11.2+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html && \
    python3 -m pip install -r requirements.txt && \
    rm torch-1.10.1+cu111-cp38-cp38-linux_x86_64.whl 

# set envs
ENV LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so

#docker build -f Dockerfile_CUDA11.1 .. -t sa/tc:torch1.10.1_py3.8_cuda11.1.1_files
